permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: zhu mingqing 
  email: zhu.mingqing2010@gmail.com

# 站点信息
title: mingqing site 
description: My personal blog
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: zhu.mingqing2010@gmail.com 
#favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: jzmq

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
